### ISSUE TITLE
Lim Dark breaks Display in gnome-control-center

### ISSUE THREAD

**Issue by EmptyVisual** [darkomarko42/Lim#3]
If the Gnome Settings application is opened on any other category other than Display, all elements seem to be themed properly, however selecting the "Display" category in settings will produce an unreadable settings page as shown below. Once "Display" is chosen, it breaks the theme for the control center no matter which category you choose beyond that point. 
This applies to Marwaita Dark, however, I've been unable to reproduce this on other third party themes.

**Power**
![image](https://user-images.githubusercontent.com/4710051/107147883-87460c80-69a4-11eb-8e36-c2b3221ac333.png)

**Once Switched to Display**
![image](https://user-images.githubusercontent.com/4710051/107147892-9331ce80-69a4-11eb-8972-61683d411495.png)

**Comment by darkomarko42** [comment]
the problem with this is that gnome apps dont follow tags on css, just follow the rgba value like( #f5f5f5 ), now is fix but it will not react to commands like (mix(@bg_color, @base_color,0.5), shade(@base_color.1.4), etc.). you should post an issue on the gnome-control-center git page
